export default {
  ADD_LIST: "ADD_LIST",
  ADD_TASK: "ADD_TASK",
  EDIT_LIST: "EDIT_LIST",
  MARK_COMPLETED: "MARK_COMPLETED",
  EDIT_TASK: "EDIT_TASK",
  REMOVE_LIST: "REMOVE_LIST",
  REMOVE_TASK: "REMOVE_TASK",
};
